### ISSUE TITLE
Convert pm25 AQI back to real pm25 level

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#46]
We use WAQI, and fetch the pm25 level from their database. However, they use a standard to transform raw pm25 level into an AQI.

We need to do the reverse calculation to get the raw pm25 level.

**Comment by jonathanrjpereira** [comment]
So does the app currently use the AQI level or raw PM2.5 level?
i.e Raw PM2.5 is measured in ug/m3.

**Comment by amaurymartiny** [comment]
aqi.

**Comment by jonathanrjpereira** [comment]
> aqi.

I thought so.

According to the WAQI website, the current AQI for my city, [Mumbai is 151](http://aqicn.org/city/india/mumbai/bandra/).
Hence by the current app implementation, the cigarette equivalence will be 151/22=6.86 Cigs.
But this value is incorrect since it is calculated using the AQI level instead of the Raw PM2.5 level.

According to [Berkley Earth](http://berkeleyearth.org/air-pollution-and-cigarette-equivalence/), 1 cigarette is equivalent to an air pollution of 22 μg/m3 for one day.

The WAQI website uses the Mumbai US Consulate Real-time Air data. According to their [website](https://in.usembassy.gov/embassy-consulates/new-delhi/air-quality-data/), they use the US Environmental Protection Agency (EPA) Air Quality Index. This [document](https://airnow.gov/sites/default/files/2018-09/aqi-technical-assistance-document-sept-2018_0.pdf) published by the EPA gives us an idea of how they convert the Raw PM2.5 level into an AQI level.

From the document, we can observe that the conversion from PM2.5 (in micrograms per cubic meter) to AQI is done in a stepwise linear manner. 

> Here is how the US Environmental Protection Agency calculates it:
> For PM2.5 between 0 and 12, the AQI is linear between 0 and 50
> For PM2.5 between 12.1 and 35.4, the AQI is linear between 51 and 100
> For PM2.5 between 35.5 and 55.4, the AQI is linear between 101 and 150
> For PM2.5 between 55.5 and 150.4, the AQI is linear between 151 and 200
> For PM2.5 between 150.5 and 250.4, the AQI is linear between 201 and 300
> For PM2.5 between 250.5 and 350.4, the AQI is linear between 301 and 400
> For PM2.5 between 350.5 and 500.4, the AQI is linear between 401 and 500
> 
> For PM2.5 greater than 500, AQI is not officially defined, but since such levels have been occurring throughout China in recent years, one of two conventions is used.  Either the AQI is defined as equal to PM2.5 (in micrograms per cubic meter) or the AQI is simply set at 500.
> Note that for PM2.5 of 12, the AQI is 50. 

This [graph](https://qph.fs.quoracdn.net/main-qimg-26951185fddf172815e70961f731301d) is a great example of the relationship between AQI & Raw PM2.5 level.

IMO we should use the standard defined by the EPA within the above-mentioned document to convert the AQI back into the Raw PM2.5 level & then further convert that value into the equivalent cigarettes.

**Comment by amaurymartiny** [comment]
Exactly! Thanks for the detailed report.

Is there any chance you would want to work on this?

**Comment by jonathanrjpereira** [comment]
I would love too, but unfortunately, I'm not well versed in JS. 

I was planning to build a Physical indicator that indicates the AQI in terms of Cigarettes using a Raspberry Pi(in Python) & some LEDs & I was doing some research on this topic when I stumbled upon your app.
